language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - yarn test
deploy:
  provider: heroku
  api_key:
    secure: J4Fa6rC8VqUBOD0nIelz4uFVPDg3SOLqJ/3S6w6/UvS0SnaIt2SeakiGNYHUu7cF/UM69MgzHqEotMEiEDjLHdRv8xNP8P3S7YPUp6o9rWFrXDhUUEo6BgL49YE1jqsAAp0/FeWULBNPwVn+Kv1UB2jeyp2MSfLtFigaTEozpp+sSO/glcjYRXNnh4XmL6MHy+JuSq/dL92f9nu06wzFiLPILps6sR3rBktDfZCxqxMsXxznPCgpyEiTnFN8FCa6dK6WJ0i3tlk1DyC5Mqv7NaqOJFt7SkAJEETYD64qkE+nlMi/oN0DzUVppvvMOMkEmYhDyrr90g/Bfe4G7rehhpw7SpO6fAnkQqIn7PQIwp3e20gbVrcL3WxmjTg4MIBI2U81yRJ09GOhADSeSPqmggdCwSho5RS45pnfrp+0Hq1q/J3cNID+vrHzKwjpjujDwXj6ZDUNGv713rf6d87ZTb4w6zqAP3Fn+S9kh7Lvj0rfvR/lCV7d2Rw9LR86UWo3nKpXykB5ayQiom6/4VNVTut9Gd2GpBVavVJMghzjJgxCqJ6Y1IEIEUgwJQhh44/wO0lyFDGnJbrH7ssf1qCpX0UlhrQGcLipQ9CrCsC7MSU1vqvYCFoK8Ujz4YJeX955TUJRgOi7q8ftgjZv3EXX4iAS7hFbrMQed00YFfP8qK8=
